@startuml

class Agent {
  name: String
  age: int
  <u>secretCode</u>: String
}

class Unit {
    <u>name</u>: String
    location: String
}

Agent "1..*" - "0..1" Unit
(Agent, Unit) "*" .. "*" Belong

class Belong {
    years: int
}
@enduml