openapi: 3.0.3
info:
  title: NiceDeals
  description: NiceDeals
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
components:
  schemas:
    Product:
      type: object
      properties:
        # todo: add constraints
        id: { type: integer, description: "The Id of the product" }
        name: { type: string, description: "The Name of the product", example: "Harry Potter" }
        price: { type: string, description: "The price of the product in dollars.", example: 10 }
        sellerId: { type: string, description: "The Id of the seller", example: "admin" }
        description: { type: string, description: "The description of the product", example: "Eum earum pariatur in sint et atque consectetur." }
        imageURL: { type: string, description: "A URL to an image", example: "http://localhost:3000/default.png"  }
        buyerId: { type: string, description: "The Id of the buyer, or null", example: null }
        purchased: { type: boolean, description: "True if purchased." }
        locked: { type: boolean, description: "True if someone else is trying to purchase it." }
    Customer:
      type: object
      properties:
        username: { type: string }
paths:
  /products:
    get:
      summary: Returns a list of products.
      responses:
        '200':
          description: A JSON array of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Creates a product.
      parameters: [ { in: cookie, name: cookie.sid, schema: { type: string } } ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                # todo: add constraints (price...) - same for patch
                name: { type: string }
                description: { type: string }
                price: { type: string }
      responses:
        '201':
          description: Created
          content: { application/json: { schema: { $ref: '#/components/schemas/Product' } } }
        '400': { description: "Invalid API usage." }
  /products/{id}:
    get:
      summary: Returns a product by ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The product's Id
          schema:
            type: integer
            format: int64
            minimum: 0
            example: 1
      responses:
        '200':
          description: OK
          content: { application/json: { schema: { $ref: '#/components/schemas/Product' } } }
        '404':
          description: A product with the specified ID was not found.
    patch:
      summary: Edit a product
      description: >
        There is no need to send unchanged properties.
        Sending `{}` works fine and changes nothing.
      parameters:
        - name: id
          in: path
          required: true
          description: The product's Id
          schema:
            type: integer
            format: int64
            minimum: 0
        - { in: cookie, name: cookie.sid, schema: { type: string } }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                description: { type: string }
                price: { type: string }
                imageURL: { type: string }
      responses:
        '200':
          description: OK
          content: { application/json: { schema: { $ref: '#/components/schemas/Product' } } }
        '400': { description: "Invalid API usage." }
        '401': { description: "Login required." }
        '403': { description: "Not allowed to edit this product." }
        '404': { description: "A product with the specified ID was not found." }
    delete:
      summary: Delete a product
      parameters:
        - $ref: '#/definitions/ProductId'
        - { in: cookie, name: cookie.sid, schema: { type: string } }
      responses:
        '200':
          description: OK
          content: { application/json: { schema: { type: boolean } } }
        '401': { description: "Login required." }
        '403': { description: "Not allowed to delete this product." }
        '404': { description: "A product with the specified ID was not found." }
  /customer:
    get:
      summary: Returns the logged customer data.
      parameters: [ { in: cookie, name: cookie.sid, schema: { type: string } } ]
      responses:
        '200':
          description: OK
          content: { application/json: { schema: { $ref: '#/components/schemas/Customer' } } }
        '401': { description: "Login required." }
  # todo: cookie
  /customer/login:
    post:
      summary: Login.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
      responses:
        '200':
          description: OK
          content: { application/json: { schema: { $ref: '#/components/schemas/Customer' } } }
        '400': { description: "Invalid API usage." }
  /customer/logout:
    post:
      summary: Logout.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: boolean
                example: true
  /stripe/checkout:
    post:
      summary: Ask for payment intent
      description: >
        Generate a payment intent and lock the product for **30** seconds. The client
        will use the payment intent's **clientSecret** to show a payment page using Stripe client.<br><br>
        Then, the `/stripe/validate` route should be called to finalize the purchase.
      parameters: [ { in: cookie, name: cookie.sid, schema: { type: string } } ]
      requestBody:
        required: true
        content:
          application/json:
            schema: { type: object, properties: { productId: { type: string } } }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  # todo: add errors
                  id: { type: string }
                  clientSecret: { type: string }
  /stripe/validate:
    post:
      summary: Validate a purchase
      description: >
        A purchase will be marked as locked, but not purchased, until the client calls /validate.<br>
        Only the payment intent Id of the `/stripe/checkout` response must be provided.
      parameters: [ { in: cookie, name: cookie.sid, schema: { type: string } } ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: { paymentIntentId: { type: string } }
              example: { paymentIntentId: 'pi_3MDdYMALDsGVpaqD0BMkf6TZ' }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: boolean
        '400': { description: "Invalid API usage." }